[config]
schemaVersion = "0.0.1"

[package]
namespace = "MT2"
name = "DiscipleClan"
versionNumber = "0.0.2"
description = "A port over of Arcadian Clan from Monster Train 1"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.7.6"
Conductor-Conductor = "0.5.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


